### PR TITLE
add reference architecture file

### PR DESCRIPTION
**Pull request by Court72**
Adding reference architecture for the new article in https://dev.azure.com/msft-skilling/Content/_workitems/edit/291712.

### CODE REVIEW

**Comment by Court72** [comment]
#sign-off

@skabou - Can you review and merge? Thanks!

**Comment by skabou** [comment]
@Court72 - I've tried opening this file a few different ways, but it keeps telling me the file is corrupt...?

**Comment by Court72** [comment]
Closing this PR - the diagram will be added as part of a separate task.

**Comment by skabou** [comment]
[like]  Jason Bouska reacted to your message:
________________________________

**Pull request closed without merging**
