### PR TITLE
CAF diagram edit request

### PR DESCRIPTION
**Pull request by cmcclister**
See https://dev.azure.com/msft-skilling/Content/_workitems/edit/214407 cc @Zimmergren @mSarts

### CODE REVIEW

**Comment by cmcclister** [comment]
@stephen-sumner please review and merge this PR when you have a chance. Thanks!

**Comment by Zimmergren** [comment]
@cmcclister , thank you for the update. 
Looks like the icon of the Azure DNS Private Resolver is still using the "Azure DNS" icon. 

Here's an example of the icon for Private Resolver: 
- https://learn.microsoft.com/en-us/azure/architecture/example-scenario/networking/media/azure-dns-private-resolver-architecture.svg

**Comment by cmcclister** [comment]
@Zimmergren I've updated the logo for Azure DNS Private Resolver in the updated Visio file.

**Comment by cmcclister** [comment]
#sign-off

**Comment by cmcclister** [comment]
#sign-off

**Comment by Zimmergren** [comment]
@cmcclister - we're awaiting final feedback and reviews on the updated file to ensure the same changes exist in this Visio as in the files changes in the CAF content repo. I'll merge this once verified, or get back with a review suggestion.

**Pull request merged**
