### PR TITLE
BUG FIX - update alz visio

### PR DESCRIPTION
**Pull request by stephen-sumner**
BUGS:
- https://github.com/MicrosoftDocs/cloud-adoption-framework/issues/1331
- https://github.com/MicrosoftDocs/cloud-adoption-framework/issues/1316

### CODE REVIEW

**Review by skabou — CHANGES_REQUESTED** [review]
@stephen-sumner I did a search of P25 in the Visio and I see one (lower left) on the tab "ALZ - Multi-Tenant - Reverse Lighthouse".  It looks like that's the only one left.

**Comment by stephen-sumner** [comment]
@skabou - let's see if that does it

**Review by skabou — APPROVED** [review]
🚀

**Comment by stephen-sumner** [comment]
#sign-off

**Comment by skabou** [comment]
#sign-off

**Pull request merged**
