### PR TITLE
Sblair01 avs visios

### PR DESCRIPTION
**Pull request by sblair01**
Adding visios per customer request

### CODE REVIEW

**Comment by sblair01** [comment]
#sign-off

**Comment by sblair01** [comment]
@BryanSoltis hello. Do you mind taking a look at this PR? Just uploading some visios for AVS LZA. Thanks!

**Comment by BryanSoltis** [comment]
Hi @sblair01,
I only focus on the Azure Naming Tool PRs, as our team created the tool and support it. @jocontr may be able to assist with general CAF PRs.
- Bryan

**Comment by sblair01** [comment]
@BryanSoltis and @jocontr - thanks for the follow up. Please let me know when this PR is close to final review. 

Thanks, 

Sabine

**Comment by BryanLa** [comment]
@sblair01 - per our email conversation on this, adding @Zimmergren for his thoughts as he is our CAF lead. I've also given him a heads up on this one.

**Pull request merged**
