### PR TITLE
Add Visio for Citrix landing zone project

### PR DESCRIPTION
**Pull request by v-thepet**
User Story https://dev.azure.com/mseng/TechnicalContent/_workitems/edit/2029621
Need to add and uncomment links to this Visio from the Citrix articles.

### CODE REVIEW

**Comment by v-thepet** [comment]
#sign-off

**Comment by v-thepet** [comment]
Hi @JanetCThomas or @jocontr - Could you merge this PR so I can add a Visio link to the Citrix Landing Zone overview article? Thanks!

**Comment by JanetCThomas** [comment]
#sign-off

**Comment by JanetCThomas** [comment]
Merged.  Please verify on the live site.

Thanks,
Janet

**Pull request merged**
