### PR TITLE
Add RHEL vsdx file referenced in new content 

### PR DESCRIPTION
**Pull request by v-regandowner**

### CODE REVIEW

**Comment by v-regandowner** [comment]
Hi @skabou,

I'm adding this file to the reference files housing repo because it is referenced in this PR https://github.com/MicrosoftDocs/cloud-adoption-framework-pr/pull/5625. Can you merge this PR? 

CC @jmart1428

**Comment by v-regandowner** [comment]
@skabou Re-pinging in case this one got lost.

**Review by skabou — CHANGES_REQUESTED** [review]
On the 2nd slide ("Hub  & Spoke") in the middle blue box (Where it says Hub VNet Region 1) -- that last line says "VPN (P25/S2S)"  it should say "VPN (P2S/S2S)"  (the letters within parentheses mean point to site / site to site.  The error is there's a 5 in there where an S should be)

**Comment by v-regandowner** [comment]
> On the 2nd slide ("Hub & Spoke") in the middle blue box (Where it says Hub VNet Region 1) -- that last line says "VPN (P25/S2S)" it should say "VPN (P2S/S2S)" (the letters within parentheses mean point to site / site to site. The error is there's a 5 in there where an S should be)

@skabou 

Fixed!

**Review by skabou — CHANGES_REQUESTED** [review]
Sorry noticed one more thing.  On each slide I see "Redhat Management and Identity"- Can you update that to "Red Hat Management and Identity"  (Red Hat should be 2 words, not 1)

**Comment by v-regandowner** [comment]
@skabou - Should be good now

**Review by skabou — APPROVED** [review]

**Comment by skabou** [comment]
Looks good! PnP #sign-off

**Pull request merged**
